name: Github Actions Test2
on: [ push ]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.action }}"
      - run: echo "${{ github.repository }}"
